import Head from 'next/head'
import { Nav } from '../components/Navbar'
import { Feature } from '../components/Feature'
import { Footer } from '../components/Footer'
import Hero from '../components/Hero'
import Cta from '../components/Cta'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Cryptocademy - Learn to invest like a pro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <Hero/>
      <Feature/>
      <Cta/>
      <Footer/>
    </div>
  )
}
